[tool.poetry]
name = "blog"
version = "0.1.0"
description = "Simple Blog"
authors = ["JaeyoungHeo <jay.jaeyoung@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
